services:
  - type: web
    name: sportrz-websockets
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ARCJET_KEY
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: ARCJET_MODE
        value: LIVE
